const endPoints = {
    LOGIN: '/login',
    FORGOT_PASSWORD: '/forgot-password',
    CHANGE_FORGOT_PASSWORD: '/change-forgot-password',
    PROFILE: '/profile',
    COMPANY: '/company',
    REASON_CODE: '/reason-code/',
    UPLOAD_FILES: '/upload',
    JOB_TITLE: '/title/',
    CLUBS: '/clubs/',
    EMPLOYEE: '/employee/',
    GET_PERMISSIONS: '/permissions/',
    SECURITY_ROLE: '/security-role/',
    DEPARTMENTS: '/department/',
    LEVELS: '/level/',
    LOCATION_TYPE: '/location-type/',
    LOCATIONS: '/location/',
    COMPAIGNS_GROUP: '/campaign-group/',
    COMPAIGN: '/campaign/',
    RESOURCE_TYPE: '/resource-type/',
    RESOURCES: '/resource/',
};
export default endPoints;
