import prof from "../assets/icons/profcard.png";

const checkInData = [
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: "04/08/2023",
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 0,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 1,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: "04/08/2023",
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 0,
    paymentDue: 1,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: null,
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 1,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: "04/08/2023",
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 0,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: "04/08/2023",
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 0,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: "04/08/2023",
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 0,
    paymentDue: 0,
  },
  {
    image: prof,
    membershipType: "Impact1",
    title: "Jerry Brown",
    date: "04/08/2023",
    time: "10:35 AM",
    checkInBefore: 2,
    isActive: 0,
    paymentDue: 0,
  },
];
export default checkInData;
