const constants = {
  base_url: "https://impactzoneapi.appdeft.biz/api/",
  image_base_url: "https://impactzoneapi.appdeft.biz/",
  // base_url: "http://localhost:1102/api/",
  // image_base_url: "http://localhost:1102/",

  endPoints: {
    Login: "gym-owner/login",
    CreateEmployee: "employee/create-employee",
    GetEmployeeTableData: "employee/employees?sortOrder=DESC",
    DeleteEmployee: "employee/delete/",
    ForgotPassword: "gym-owner/forget-password",
    CreateNewPassword: "gym-owner/change-forget-password",
    OtpVerfiy: "gym-owner/verify-otp",
    GetDepartment: "departments",
    CreateDepartment: "departments",
    JobTitle: "gym-owner/titles",
    CreateJobTitle: "gym-owner/title",
    DeleteTitle: "gym-owner/title/delete/",
    DeleteDepartment: "departments/delete/",
    TitleUpdate: "gym-owner/title/update/",
    UpdateDepartment: "departments/update/",
    GetClubs: "gym-owner/clubs",
    AddLevel: "levels",
    DeleteLevel: "levels/delete/",
    UpdateLevel: "levels/update/",
    uploadFile: "upload",
    getEmployee: "employee/get-employee",
    updateEmployee: "employee/update",
    locationTypes: "locations/types",
    updateLocationType: "locations/types/update/",
    deleteLocationType: "locations/types/delete/",
    locations: "locations",
    updateLocation: "locations/update/",
    deleteLocation: "locations/delete/",
    allEvents: "events",
    UpdateEvent: "events/update/",
    DeleteEvent: "events/delete/",
    getEventsByType: "events/getByType/",
    classSchedules: "class-schedules",
    updateClassSchedules: "class-schedules/update/",
    deleteClassSchedule: "class-schedules/delete/",
    getEventCategories: "events/categories",
    addEventCategory: "events/category",
    updatEventCategory: "events/category/update/",
    deleteEventCategory: "events/category/delete/",
    resourceType: "resource-types",
    DeleteResourceType: "resource-types/delete/",
    UpdateResourceType: "resource-types/update/",
    UpdateCampaign: "campaigns/update/",
    DeleteCampaign: "campaigns/delete/",
    resources: "resources/",
    UpdateResource: "resources/update/",
    DeleteResource: "resources/delete/",
    MemberShipType: "membership-types",
    UpdateMemberShipType: "membership-types/update/",
    DeleteMemberShipType: "membership-types/delete/",
    AllCampaignGroups: "campaign-groups",
    UpdateCampaignGroups: "campaign-groups/update/",
    DeleteCampaignGroups: "campaign-groups/delete/",
    AllCampaign: "campaigns",
    AccessSchedules: "access-schedules",
    UpdateAccessSchedule: "access-schedules/update/",
    DeleteAccessSchedule: "access-schedules/delete/"
  },

  calendarDefaultWeek: {
    start: "2023-10-01"
  }
};

export default constants;
