export const types = {
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
  SHOW_TOAST: "SHOW_TOAST",

  //  LOCATION TYPES //
  LOCATION_TYPES: "LOCATION_TYPES",

  // LOCATIONS //
  LOCATIONS: "LOCATIONS",
  EVENTS: "EVENTS",
  ADD_EVENT:"ADD_EVENT",
  EVENT_DURATIONS:"EVENT_DURATIONS",
  EVENT_CALENDARDISPLAY:"EVENT_CALENDARDISPLAY",
  EVENT_POPUPDISPLAY:"EVENT_POPUPDISPLAY",
  EVENT_DEPLOYEDCLUBS:"EVENT_DEPLOYEDCLUBS",
  LEVELS:"LEVELS",

  // CLUBS //
  CLUBS: "CLUBS",
};
