import Divide from "../../../../../../assets/icons/box.png";

export const paymentOptions = [
  {
    name: "Incremental Pay",
    key: "increamentalPay",
    fields: [
      {
        name: "1-5 Clients",
        key: "1To5Clients",
        type: "number",
        width: "5rem",
        dollarsign: true,
      },
      {
        name: "6-10 Clients",
        key: "6To10Clients",
        type: "number",
        width: "5rem",
        dollarsign: true,
      },
      {
        name: "11-15 Clients",
        key: "11To15Clients",
        type: "number",
        width: "5rem",
        dollarsign: true,
      },
      {
        name: "16-20 Clients",
        key: "16To20Clients",
        type: "number",
        width: "5rem",
        dollarsign: true,
      },
      {
        name: "21-25 Clients",
        key: "21To25Clients",
        type: "number",
        width: "5rem",
        dollarsign: true,
      },
      {
        name: "26+ Clients",
        key: "26PlusClients",
        type: "number",
        width: "5rem",
        dollarsign: true,
      },
      {
        name: "No Registration Pay",
        key: "noRegisterationPay",
        type: "number",
        width: "5rem",
        dollarsign: true,
      },
      {
        name: "Count Unpaid Services",
        key: "countUnpaidServices",
        type: "checkbox",
        width: "4rem",
        dollarsign: true,
      },
    ],
  },
  {
    name: "Pay Per Class",
    key: "payPerClass",
    fields: [
      {
        name: "Pay Per Class",
        key: "payPerClass",
        type: "number",
        dollarsign: true,
      },
      {
        name: "No Registration Pay",
        key: "noRegisterationPay",
        type: "number",
        dollarsign: true,
      },
    ],
  },
  {
    name: "Pay Per Client",
    key: "payPerClient",
    fields: [
      {
        name: "Base Rate",
        key: "baseRate",
        type: "number",
        width: "3rem",
        dollarsign: false,
      },
      {
        name: "Per Client",
        key: "perClient",
        type: "number",
        width: "3rem",
        dollarsign: false,
      },
      {
        name: "For each client over",
        key: "forEachClientOver1",
        type: "dropdown",
        width: "3rem",
        orderInRow: 1,
        dollarsign: false,
      },
      {
        name: "Add",
        key: "add1",
        type: "number",
        width: "3rem",
        dollarsign: false,
      },
      {
        name: "For each client over",
        key: "forEachClientOver2",
        type: "dropdown",
        width: "3rem",
        orderInRow: 2,
        dollarsign: false,
      },
      {
        name: "Add",
        key: "add2",
        type: "number",
        width: "3rem",
        dollarsign: false,
      },
      {
        name: "For each client over",
        key: "forEachClientOver3",
        type: "dropdown",
        width: "3rem",
        orderInRow: 3,
        dollarsign: false,
      },
      {
        name: "Add",
        key: "add3",
        type: "number",
        width: "3rem",
        dollarsign: false,
      },
      {
        name: "No Registration Pay",
        key: "noRegisterationPay",
        type: "number",
        width: "3rem",
        dollarsign: false,
      },
      {
        name: "Max Pay",
        key: "maxPay",
        type: "number",
        width: "3rem",
        dollarsign: false,
      },
      {
        name: "Count Unpaid Services",
        key: "countUnpaidServices",
        type: "checkbox",
      },
    ],
  },
  {
    name: "% Rate",
    key: "percentRate",
    fields: [
      {
        name: "% Rate",
        key: "percentRate",
        type: "number",
        dollarsign: false,
      },
      {
        name: "No Registration Pay",
        key: "noRegisterationPay",
        type: "number",
        dollarsign: false,
      },
    ],
  },
];
